server:
#  port: 8082
  port: 5000
  servlet:
    context-path: /
serverUrl: http://localhost:3000
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://appservice.coa06awz157e.us-east-1.rds.amazonaws.com:3306/app_service?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: quangvinh17112K
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3307/app_service?allowPublicKeyRetrieval=true&useSSL=false
#    username: root
#    password: 889910
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 855424384714-2n7ahd5moi5675f7bo8cie7nl28mvmuv.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 1294673631321588
            clientSecret: b86dae3a4681f7a07be3b5cb981493d1
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: dffa756c43de1df7ee44
            clientSecret: a97ff87cec3ab6c9096751730f020801f4117334
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:3001, http://localhost:3002, http://localhost:8080, http://client-env.eba-ipnpmt7c.us-east-1.elasticbeanstalk.com
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
paypal:
  clientId: AY71RNcjABIXpStOyxscOnhDZbNfP9C5NwxbpdII9QeY8xixFkLc8yHLM_K65iTfnUATB2PnAQWTeFvr
  clientSecret: EONUD4-ObRB9gl_r5pcGkk2FhAE49sVbfWmeALl9cNDK1-aLdHnt0IZTdk3x_QypIs854CiH3Yqz5qL-
  environmentMode: sandbox
cloud:
  name: divmj7rv7
  secret: Hg7oKtmZEjukvrcJvW-5jRVFR-g
  key: 729439797434637